name: "Build and Tag Release Candidate"
on:
  push:
    branches:
      - main
    paths-ignore: # Only run checks on changes to code
      - "**/docs/*"
      - "*/README.md"

jobs:
  build:
    name: "Create Release Candidate"
    runs-on: [ubuntu-22.04]
    env:
      ACCOUNT_ID: "TSampley@gmail.com" # TODO: create/use service account
      APP_ID: "org.pointyware.painteddogs"
      BUNDLE_ID: "org.pointyware.painteddogs"
      PROJECT_ID: "painted-dogs-prod"
    outputs:
      BUNDLE_NAME: ${{ steps.build.outputs.bundle_name }}
      BUNDLE_PATH: ${{ steps.build.outputs.bundle_path }}

    steps:
      - name: "Setup - Checkout Project"
        uses: actions/checkout@v4
      - name: "Setup - Java 17"
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: "Setup - Gradle"
        uses: gradle/actions/setup-gradle@v3

      - name: "Setup - Keystore"
        env:
          RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
        run: |
          echo "$RELEASE_KEYSTORE" | base64 --decode > release.keystore

      - name: "Build - Release"
        id: build
        env:
          ALIAS_PASS: ${{ secrets.ALIAS_PASS }}
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          GENERATED_OUTPUT_NAME: app-android-release.aab
          GENERATED_OUTPUT_PATH: app-android/build/outputs/bundle/release
          FINAL_OUTPUT_NAME: "app-android-rc-${{ github.sha }}"
          FINAL_OUTPUT_PATH: outputs
        run: |
          ./gradlew buildRelease \
            -DkeystoreReleasePass="$KEYSTORE_PASS" \
            -DkeystoreReleasePaintedDogsPass="$ALIAS_PASS" \
            -DbuildSuffix="$BUILD_SUFFIX" \
          && \
            mkdir -p "$FINAL_OUTPUT_PATH"
          && \
            mv "$GENERATED_OUTPUT_PATH/$GENERATED_OUTPUT_NAME" \
              "$FINAL_OUTPUT_PATH/$FINAL_OUTPUT_NAME" \
          && \
            echo "BUNDLE_NAME=$FINAL_OUTPUT_NAME" >> "$GITHUB_OUTPUT" \
          && \
            echo "BUNDLE_PATH=$FINAL_OUTPUT_PATH" >> "$GITHUB_OUTPUT"

      - name: "Distribute - Google Play"
        run: |
          BINARY="$FINAL_OUTPUT_PATH/$FINAL_OUTPUT_NAME"
          TOKEN="$(gcloud auth application-default print-access-token)"
          
          # Call Edits:Insert
          
          # Call Edits.bundles:Upload
          # Call Edits.tracks:Update
          # Call Edits.listings:Update/Patch
          
          # Call Edits:Commit
          
          curl -X POST \
            -H "X-Goog-User-Project: $PROJECT_ID" \
            -H "Authorization: Bearer $TOKEN" \
            
            https://androidpublisher.googleapis.com/upload/androidpublisher/v3/applications/$BUNDLE_ID/edits/{editId}/bundles
